apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: "{{.Values.namespace}}"
  name: {{include "cfddns.fullname" .}}
  labels: {{- include "cfddns.labels" . | nindent 4}}
spec:
  schedule: "{{.Values.schedule}}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{.Values.image.restartPolicy}}
          containers:
            - name: "{{.Values.podName}}"
              image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
              imagePullPolicy: {{.Values.image.pullPolicy}}
              envFrom:
                - secretRef:
                    name: {{include "cfddns.fullname" .}}
                - configMapRef:
                    name: {{include "cfddns.fullname" .}}