apiVersion: v1
kind: Secret
metadata:
  namespace: {{include "cfddns.fullname" .}}
  name: {{include "cfddns.fullname" .}}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
