apiVersion: v1
kind: Secret
metadata:
  namespace: "{{.Values.namespace}}"
  name: {{include "cfddns.fullname" .}}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}