# Default values for cfddns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
podName: "cf-ddclient"

image:
  repository: zaptross/cfddns
  pullPolicy: IfNotPresent
  restartPolicy: OnFailure
  tag: latest

env:
  TOKEN: "<your_api_token_here>"
  DOMAIN: "<your_domain_here>"
  SUBDOMAIN: "<your_subdomain_here>"
  PROXY: "<true | false>"
  COMMENT: "<true | false>"

schedule: "*/5 * * * *"
