# Default values for cfddns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
podName: "cf-ddclient"

image:
  repository: zaptross/cfddns
  pullPolicy: IfNotPresent
  restartPolicy: OnFailure
  tag: latest

env:
  CLOUDFLARE_TOKEN: "<your_api_token_here>"
  CLOUDFLARE_DOMAIN: "<your_domain_here>"
  CLOUDFLARE_SUBDOMAIN: "<your_subdomain_here>"
  CLOUDFLARE_PROXY: "<true | false>"
  CLOUDFLARE_COMMENT: "<true | false>"

schedule: "*/5 * * * *"
